(FUNCTION  fact  [(int x)]
  (BB 2
    (OPER 3 Func_Entry []  [])
  )
  (BB 3
    (OPER 5 Mov [(r 5)]  [(i 1)])
    (OPER 6 GT [(r 4)]  [(r 1)(r 5)])
    (OPER 4 BEQ []  [(r 4)(i 0)(bb 5)])
  )
  (BB 4
    (OPER 7 Mov [(r 8)]  [(i 48)])
    (OPER 8 Add_I [(r 7)]  [(r 8)(r 1)])
    (OPER 9 Pass []  [(r 7)])
    (OPER 10 JSR []  [(s putchar)])
    (OPER 11 Mov [(r 9)]  [(m RetReg)])
    (OPER 12 Mov [(r 13)]  [(i 1)])
    (OPER 13 Sub_I [(r 12)]  [(r 1)(r 13)])
    (OPER 14 Pass []  [(r 12)])
    (OPER 15 JSR []  [(s fact)])
    (OPER 16 Mov [(r 14)]  [(m RetReg)])
    (OPER 17 Mul_I [(r 11)]  [(r 1)(r 14)])
    (OPER 18 Mov [(r 3)]  [(r 11)])
    (OPER 19 Mov [(r 16)]  [(i 48)])
    (OPER 20 Add_I [(r 15)]  [(r 16)(r 3)])
    (OPER 21 Pass []  [(r 15)])
    (OPER 22 JSR []  [(s putchar)])
    (OPER 23 Mov [(r 17)]  [(m RetReg)])
    (OPER 24 Mov [(m RetReg)]  [(r 3)])
    (OPER 25 Jmp []  [(bb 1)])
  )
  (BB 6
  )
  (BB 1
    (OPER 1 Func_Exit []  [])
    (OPER 2 Return []  [(m RetReg)])
  )
  (BB 5
    (OPER 26 Mov [(r 19)]  [(i 49)])
    (OPER 27 Pass []  [(r 19)])
    (OPER 28 JSR []  [(s putchar)])
    (OPER 29 Mov [(r 20)]  [(m RetReg)])
    (OPER 30 Mov [(r 21)]  [(i 1)])
    (OPER 31 Mov [(m RetReg)]  [(r 21)])
    (OPER 32 Jmp []  [(bb 1)])
  )
)
(FUNCTION  main  []
  (BB 2
    (OPER 3 Func_Entry []  [])
  )
  (BB 3
    (OPER 4 Mov [(r 4)]  [(i 3)])
    (OPER 5 Mov [(r 2)]  [(r 4)])
    (OPER 6 Pass []  [(r 2)])
    (OPER 7 JSR []  [(s fact)])
    (OPER 8 Mov [(r 6)]  [(m RetReg)])
    (OPER 9 Mov [(r 2)]  [(r 6)])
    (OPER 10 Mov [(r 8)]  [(i 48)])
    (OPER 11 Add_I [(r 7)]  [(r 8)(r 2)])
    (OPER 12 Pass []  [(r 7)])
    (OPER 13 JSR []  [(s putchar)])
    (OPER 14 Mov [(r 9)]  [(m RetReg)])
    (OPER 15 Mov [(r 10)]  [(i 10)])
    (OPER 16 Pass []  [(r 10)])
    (OPER 17 JSR []  [(s putchar)])
    (OPER 18 Mov [(r 11)]  [(m RetReg)])
  )
  (BB 1
    (OPER 1 Func_Exit []  [])
    (OPER 2 Return []  [(m RetReg)])
  )
)
